name: apby
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.16.0
  flutter_local_notifications: ^1.4.3
  cached_network_image: ^2.1.0+1
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  photo_view: ^0.9.2
  url_launcher: ^5.4.10
  fluttertoast: ^7.1.5
  keyboard_actions: ^3.3.0+1
  shared_preferences: ^0.5.7+1
  firebase_messaging: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
   
  # To add assets to your application, add an assets section, like this:
  assets: 
    - images/001-panda.png
    - images/002-lion.png
    - images/003-tiger.png
    - images/004-bear-1.png
    - images/005-parrot.png
    - images/006-rabbit.png
    - images/007-chameleon.png
    - images/008-sloth.png
    - images/009-elk.png
    - images/010-llama.png
    - images/011-ant-eater.png
    - images/012-eagle.png
    - images/013-crocodile.png
    - images/014-beaver.png
    - images/015-hamster.png
    - images/016-walrus.png
    - images/017-bear.png
    - images/018-cheetah.png
    - images/019-kangaroo.png
    - images/020-duck.png
    - images/021-goose.png
    - images/022-lemur.png
    - images/023-ostrich.png
    - images/024-owl.png
    - images/026-penguin.png
    - images/025-boar.png
    - images/027-camel.png
    - images/028-raccoon.png
    - images/029-hippo.png
    - images/030-monkey.png
    - images/031-meerkat.png
    - images/032-snake.png
    - images/033-zebra.png
    - images/034-donkey.png
    - images/035-bull.png
    - images/036-goat-1.png
    - images/037-goat.png
    - images/038-horse.png
    - images/039-wolf.png
    - images/040-koala.png
    - images/041-hedgehog.png
    - images/042-frog.png
    - images/043-turtle.png
    - images/044-gorilla.png
    - images/045-giraffe.png
    - images/046-deer.png
    - images/047-rhinoceros.png
    - images/048-elephant.png
    - images/049-puma.png
    - images/050-fox.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
